version: "3.1"

services:
  # 单注册中心版本
  # zoo1:
  #   image: qtrj.i234.me:8084/zookeeper
  #   restart: always
  #   stdin_open: true
  #   tty: true
  #   hostname: zoo1
  #   ports:
  #     - 2181:2181
  #   # volumes:
  #   #   - ./zoo1/conf:/conf
  #   #   - ./zoo1/data:/data
  #   #   - ./zoo1/datalog:/datalog
  #   environment:
  #     ZOO_4LW_COMMANDS_WHITELIST: "*"
  # 多注册中心版本
  zoo1:
    image: qtrj.i234.me:8084/zookeeper
    restart: always
    stdin_open: true
    tty: true
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_4LW_COMMANDS_WHITELIST: "*"
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    image: qtrj.i234.me:8084/zookeeper
    restart: always
    stdin_open: true
    tty: true
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_4LW_COMMANDS_WHITELIST: "*"
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    image: qtrj.i234.me:8084/zookeeper
    restart: always
    stdin_open: true
    tty: true
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_4LW_COMMANDS_WHITELIST: "*"
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181

  admin:
    image: qtrj.i234.me:8084/chenchuxin/dubbo-admin
    # build: ./dubbo-admin/
    restart: always
    stdin_open: true
    tty: true
    hostname: admin
    ports:
      - 8080:8080
    environment:
      dubbo.admin.root.password: 123456
      dubbo.registry.address: zookeeper://zoo1:2181|zookeeper://zoo2:2181|zookeeper://zoo3:2181
